from collections import defaultdict

DB_LOCATION = 'lolreplaysite/databases/lolreplaysite.gd'
MAIN_MENU_ITEMS = (
				{'name': 'Replays',
				'href': '/replays',
				},
				{'name': 'FAQ',
				'href': '/faq'
				},
				{'name': 'Feedback',
				'href': '/feedback',
				},
				{'name': 'Upload',
				'href': '/upload',
				}
				)
USER_MENU_ITEMS = (
				{
				'name': 'Notifications',
				'src': '{mail_icon}',
				'href': '/users/{userid}/{username}/notifications',
				},
				{
				'name': 'Your Replays',
				'href': '/users/{userid}/{username}/replays',
				},
				{
				'name': 'Your Reviews',
				'href': '/users/{userid}/{username}/reviews',
				},
				)
REPLAY_FOLDER_LOCATION = 'lolreplaysite/replays/'
HEROES = defaultdict(int, {
						'ahri':103,
						'akali':84,
						'alistar':12,
						'amumu':32,
						'anivia':34,
						'annie':1,
						'ashe':22,
						'blitzcrank':53,
						'brand':63,
						'caitlyn':51,
						'cassiopeia':69,
						"chogath":31,
						"corki":42,
						'drmundo':36,
						'evelynn':28,
						'ezreal':81,
						'fiddlesticks':9,
						'fiora':114,
						'fizz':105,
						'galio':3,
						'gangplank':41,
						'garen':86,
						'gragas':79,
						'graves':104,
						'heimerdinger':74,
						'irelia':39,
						'janna':40,
						'jarvaniv':59,
						'jax':24,
						'karma':43,
						'karthus':30,
						'kassadin':38,
						'katarina':55,
						'kayle':10,
						'kennen':85,
						"kogmaw":96,
						'leblanc':7,
						'leesin':64,
						'leona':89,
						'lulu':117,
						'lux':99,
						'malphite':54,
						'malzahar':90,
						'maokai':57,
						'masteryi':11,
						'missfortune':21,
						'mordekaiser':82,
						'morgana':25,
						'nasus':75,
						'nautilus':111,
						'nidalee':76,
						'nocturne':56,
						'nunu':20,
						'olaf':2,
						'orianna':61,
						'pantheon':80,
						'poppy':78,
						'rammus':33,
						'renekton':58,
						'riven':92,
						'rumble':68,
						'ryze':13,
						'sejuani':113,
						'shaco':34,
						'shen':98,
						'shyvana':102,
						'singed':27,
						'sion':14,
						'sivir':15,
						'skarner':72,
						'sona':37,
						'soraka':16,
						'swain':50,
						'talon':91,
						'taric':44,
						'teemo':17,
						'tristana':18,
						'trundle':48,
						'tryndamere':23,
						'twisted fate':4,
						'twitch':29,
						'udyr':77,
						'urgot':6,
						'vayne':67,
						'veigar':45,
						'viktor':112,
						'vladimir':8,
						'volibear':106,
						'warwick':19,
						'wukong':62,
						'xerath':101,
						'xinzhao':5,
						'yorick':83,
						'ziggs':115,
						'zilean':26,
						}
					)